import React, { useMemo, useState } from "react";
import { CalendarDays, CheckCircle2, Clock3, ChevronDown, Copy, Eye, FileText, Link2, Plus, Save, Search, Send, X } from "lucide-react";
import { formatDate, normalizeText } from "./domain";
import { buildQuoteEmailHtml, copyQuoteToClipboard, QUOTE_CHANNELS, QUOTE_PRIORITIES, QUOTE_STATUSES, quoteSubject, validateQuoteDraft } from "./quoteDomain";

const QUOTE_SORT_COLUMNS = [["code", "Cotação"], ["client", "Cliente"], ["status", "Status"], ["deadline", "Prazo"], ["value", "Valor"]];
const OPEN_STATUSES = new Set(["Nova", "Em análise pelo financeiro", "Aguardando informação", "Cotada"]);

function todayKey() {
  const parts = new Intl.DateTimeFormat("en-US", { timeZone: "America/Sao_Paulo", year: "numeric", month: "2-digit", day: "2-digit" }).formatToParts(new Date());
  const values = Object.fromEntries(parts.map((part) => [part.type, part.value]));
  return `${values.year}-${values.month}-${values.day}`;
}
function isOpenQuote(quote) { return OPEN_STATUSES.has(quote?.status); }
function isOverdueQuote(quote) { return Boolean(quote?.deadline) && isOpenQuote(quote) && quote.deadline < todayKey(); }
function statusTone(status) { const value = normalizeText(status); if (value.includes("respondida") || value.includes("convertida")) return "success"; if (value.includes("aguardando")) return "warning"; if (value.includes("analise") || value === "cotada") return "action"; if (value.includes("perdida") || value.includes("cancelada")) return "danger"; return "neutral"; }
function QuoteStatus({ status }) { return <span className={`quote-status quote-status-${statusTone(status)}`}><span className="badge-dot" />{status || "Sem status"}</span>; }
function quoteSortValue(quote, key) { if (key === "deadline") return quote.deadline || "9999-12-31"; if (key === "value") { const value = Number.parseFloat(String(quote.value || "").replace(/[^0-9,-]/g, "").replace(/\./g, "").replace(",", ".")); return Number.isNaN(value) ? -1 : value; } return normalizeText(quote[key]); }
function compareQuotes(left, right, key) { const a = quoteSortValue(left, key); const b = quoteSortValue(right, key); return typeof a === "number" && typeof b === "number" ? a - b : String(a).localeCompare(String(b), "pt-BR"); }
function Field({ label, required, children, wide = false }) { return <label className={wide ? "quote-field-wide" : ""}>{label}{required && <span className="required-mark"> *</span>}{children}</label>; }

function QuoteWorkspace({ quote, employees = [], onBack, onSave, onMarkSent, onOutcome, saving = false }) {
  const [draft, setDraft] = useState(() => ({ status: "Nova", priority: "medium", channel: "WhatsApp", ...(quote || {}) }));
  const [preview, setPreview] = useState(false);
  const [copying, setCopying] = useState(false);
  const [feedback, setFeedback] = useState("");
  const update = (key, value) => setDraft((current) => ({ ...current, [key]: value }));
  const submit = (event) => { event.preventDefault(); const validation = validateQuoteDraft(draft); if (!validation.valid) { setFeedback(validation.error); return; } setFeedback(""); onSave?.(draft); };
  const handleCopy = async () => { try { setCopying(true); await copyQuoteToClipboard(draft, { baseUrl: window.location.origin }); setFeedback("Cotação copiada. Cole no corpo de uma nova mensagem do Outlook."); } catch (error) { setFeedback(error.message); } finally { setCopying(false); } };
  const handleMarkSent = () => { update("responseSent", true); update("status", "Respondida ao cliente"); onMarkSent?.(quote.id); };
  const handleOutcome = (outcome, reason = "") => { update("status", outcome); update("lossReason", reason); onOutcome?.(quote.id, outcome, reason); };
  const canCopy = draft.status === "Cotada" && String(draft.value || "").trim();
  const previewHtml = buildQuoteEmailHtml(draft, { baseUrl: typeof window !== "undefined" ? window.location.origin : "" });
  return <section className="panel quote-workspace" role="dialog" aria-modal="true" aria-label={quote ? `Editar cotação ${quote.code}` : "Nova cotação"}>
    <header className="quote-workspace-header"><div><button className="button button-quiet" type="button" onClick={onBack}>← Voltar para a lista</button><span className="eyebrow">{quote ? "EDIÇÃO OPERACIONAL" : "NOVA SOLICITAÇÃO"}</span><h2>{quote ? `${quote.code || "Cotação"} · editar` : "Criar cotação"}</h2></div><div className="quote-workspace-actions"><button className="button button-secondary" type="button" onClick={() => setPreview((value) => !value)}><Eye size={15} />{preview ? "Ocultar prévia" : "Prévia do e-mail"}</button>{quote?.id && canCopy && <button className="button button-secondary" type="button" onClick={handleCopy} disabled={copying}><Copy size={15} />{copying ? "Copiando…" : "Copiar para Outlook"}</button>}<button className="button button-primary" type="submit" form="quote-workspace-form" disabled={saving}><Save size={15} />{saving ? "Salvando…" : "Salvar cotação"}</button></div></header>
    <div className="quote-workspace-layout"><form id="quote-workspace-form" className="quote-form" onSubmit={submit}>
      <div className="quote-form-section"><span className="eyebrow">IDENTIFICAÇÃO</span><Field label="Título interno" required wide><input required value={draft.title || ""} onChange={(event) => update("title", event.target.value)} placeholder="Ex.: Transfer executivo · Aeroporto GRU" /></Field><div className="quote-form-grid"><Field label="Status"><select value={draft.status || "Nova"} onChange={(event) => update("status", event.target.value)}>{QUOTE_STATUSES.map((item) => <option key={item}>{item}</option>)}</select></Field><Field label="Prioridade"><select value={draft.priority || "medium"} onChange={(event) => update("priority", event.target.value)}>{QUOTE_PRIORITIES.map((item) => <option key={item.id} value={item.id}>{item.label}</option>)}</select></Field><Field label="Responsável"><select value={draft.assigneeId || ""} onChange={(event) => { const employee = employees.find((item) => item.id === event.target.value); update("assigneeId", event.target.value); update("assigneeIds", event.target.value ? [event.target.value] : []); update("assigneeNames", employee ? [employee.name] : []); }}><option value="">Não atribuído</option>{employees.map((employee) => <option key={employee.id} value={employee.id}>{employee.name}</option>)}</select></Field></div></div>
      <div className="quote-form-section"><span className="eyebrow">CLIENTE E ENTRADA</span><div className="quote-form-grid"><Field label="Cliente / empresa" required><input required value={draft.client || ""} onChange={(event) => update("client", event.target.value)} /></Field><Field label="Contato" required><input required value={draft.clientContact || ""} onChange={(event) => update("clientContact", event.target.value)} /></Field><Field label="Canal de entrada" required><select required value={draft.channel || ""} onChange={(event) => update("channel", event.target.value)}><option value="">Selecione</option>{QUOTE_CHANNELS.map((item) => <option key={item}>{item}</option>)}</select></Field><Field label="WhatsApp / telefone"><input type="tel" value={draft.clientPhone || ""} onChange={(event) => update("clientPhone", event.target.value)} /></Field><Field label="E-mail"><input type="email" value={draft.clientEmail || ""} onChange={(event) => update("clientEmail", event.target.value)} /></Field></div></div>
      <div className="quote-form-section"><span className="eyebrow">SERVIÇO</span><div className="quote-form-grid"><Field label="Tipo de serviço" required><input required value={draft.serviceType || ""} onChange={(event) => update("serviceType", event.target.value)} placeholder="Transfer executivo" /></Field><Field label="Tipo de veículo"><input value={draft.vehicleType || ""} onChange={(event) => update("vehicleType", event.target.value)} placeholder="Van executiva" /></Field><Field label="Origem" required><input required value={draft.origin || ""} onChange={(event) => update("origin", event.target.value)} /></Field><Field label="Destino" required><input required value={draft.destination || ""} onChange={(event) => update("destination", event.target.value)} /></Field><Field label="Data e hora do serviço" required><input required type="datetime-local" value={draft.serviceDate || ""} onChange={(event) => update("serviceDate", event.target.value)} /></Field><Field label="Passageiros"><input type="number" min="1" value={draft.passengers || ""} onChange={(event) => update("passengers", event.target.value)} /></Field><Field label="Possui retorno"><span className="quote-checkbox-field"><input type="checkbox" checked={Boolean(draft.hasReturn || draft.returnDate)} onChange={(event) => { update("hasReturn", event.target.checked); if (!event.target.checked) update("returnDate", ""); }} /> Sim</span></Field><Field label="Data e hora do retorno"><input type="datetime-local" disabled={!draft.hasReturn && !draft.returnDate} value={draft.returnDate || ""} onChange={(event) => { update("returnDate", event.target.value); update("hasReturn", Boolean(event.target.value)); }} /></Field><Field label="Prazo para responder" required><input required type="date" value={draft.deadline || ""} onChange={(event) => update("deadline", event.target.value)} /></Field><Field label="Observações do pedido" wide><textarea rows={3} value={draft.notes || ""} onChange={(event) => update("notes", event.target.value)} /></Field></div></div>
      <div className="quote-form-section"><span className="eyebrow">COMERCIAL</span><div className="quote-form-grid"><Field label="Valor total (BRL)"><input value={draft.value || ""} onChange={(event) => update("value", event.target.value)} placeholder="R$ 0,00" /></Field><Field label="Condição comercial" wide><textarea rows={3} value={draft.commercialTerms || ""} onChange={(event) => update("commercialTerms", event.target.value)} placeholder="Validade, pagamento e condições acordadas" /></Field>{draft.status === "Perdida" && <Field label="Motivo da perda" required wide><textarea required rows={2} value={draft.lossReason || ""} onChange={(event) => update("lossReason", event.target.value)} /></Field>}</div></div>
      {feedback && <p className="quote-form-feedback" role="status">{feedback}</p>}
    </form>{preview && <aside className="quote-email-preview" aria-label="Prévia do e-mail da cotação"><div className="quote-email-preview-bar"><span>Prévia fiel do modelo</span><small>{quoteSubject(draft)}</small></div><iframe title="Prévia da tabela para Outlook" srcDoc={previewHtml} className="quote-email-iframe" /></aside>}</div>
    {quote?.id && <footer className="quote-workspace-footer"><span className="quote-form-hint">Equipe padrão: Financeiro · Copiar não altera o status.</span><div className="quote-outcome-actions">{draft.status === "Cotada" && <button className="button button-secondary" type="button" onClick={handleCopy} disabled={!canCopy || copying}><Copy size={15} />Copiar cotação</button>}{!draft.responseSent && <button className="button button-secondary" type="button" onClick={handleMarkSent}><Send size={15} />Marcar como enviada</button>}<button className="button button-secondary" type="button" onClick={() => handleOutcome("Convertida em serviço")}><CheckCircle2 size={15} />Marcar aceite</button><button className="button button-danger" type="button" onClick={() => { const reason = window.prompt("Motivo da perda"); if (reason) handleOutcome("Perdida", reason); }}><X size={15} />Marcar perdida</button></div></footer>}
  </section>;
}

export default function QuotesView({ state, onOpenTask, onCreateQuote, onUpdateQuote, onMarkQuoteSent, onSetQuoteOutcome, workspaceEnabled = true }) {
  const [query, setQuery] = useState(""); const [status, setStatus] = useState(""); const [sort, setSort] = useState({ key: "", direction: "asc" }); const [selectedQuote, setSelectedQuote] = useState(null); const [editingQuote, setEditingQuote] = useState(null); const [savingQuote, setSavingQuote] = useState(false);
  const quotes = state.quotes || []; const tasksByQuote = useMemo(() => new Map((state.tasks || []).filter((task) => task.quoteId).map((task) => [task.quoteId, task])), [state.tasks]);
  const statuses = useMemo(() => [...QUOTE_STATUSES.filter((item) => quotes.some((quote) => quote.status === item)), ...quotes.map((quote) => quote.status).filter((item, index, all) => item && !QUOTE_STATUSES.includes(item) && all.indexOf(item) === index)], [quotes]);
  const filteredQuotes = useMemo(() => { const needle = normalizeText(query); const rows = quotes.filter((quote) => (!needle || [quote.code, quote.title, quote.client, quote.status].some((value) => normalizeText(value).includes(needle))) && (!status || quote.status === status)); if (!sort.key) return rows; const direction = sort.direction === "desc" ? -1 : 1; return [...rows].sort((a, b) => compareQuotes(a, b, sort.key) * direction); }, [query, quotes, sort, status]);
  const metrics = useMemo(() => ({ total: quotes.length, open: quotes.filter(isOpenQuote).length, answered: quotes.filter((quote) => normalizeText(quote.status) === "respondida ao cliente").length, overdue: quotes.filter(isOverdueQuote).length }), [quotes]);
  const selectedTask = selectedQuote ? tasksByQuote.get(selectedQuote.id) : null;
  const openEditor = (quote) => { setSelectedQuote(null); setEditingQuote(quote); };
  return <div className="page-content quotes-page" data-view="quotes"><div className="page-header"><div><span className="eyebrow">ACOMPANHAMENTO COMERCIAL</span><h1>Cotações</h1><p>Registre o pedido, acompanhe o Financeiro e prepare a resposta para o Outlook.</p></div>{workspaceEnabled && <button className="button button-primary" type="button" onClick={() => setEditingQuote({})}><Plus size={15} />Nova cotação</button>}</div>
    <div className="metric-grid quotes-metrics"><div className="metric-card metric-navy"><div className="metric-icon"><FileText size={18} /></div><div><span>Total</span><strong>{metrics.total}</strong></div></div><div className="metric-card metric-action"><div className="metric-icon"><Clock3 size={18} /></div><div><span>Em andamento</span><strong>{metrics.open}</strong></div></div><div className="metric-card metric-success"><div className="metric-icon"><CheckCircle2 size={18} /></div><div><span>Respondidas</span><strong>{metrics.answered}</strong></div></div><div className="metric-card metric-danger"><div className="metric-icon"><CalendarDays size={18} /></div><div><span>Prazo vencido</span><strong>{metrics.overdue}</strong></div></div></div>
    <section className="panel quotes-panel"><div className="panel-heading quotes-panel-heading"><div><span className="eyebrow">REGISTROS DISPONÍVEIS</span><h2>Base de cotações</h2></div><span className="panel-count">{filteredQuotes.length}</span></div><div className="quotes-toolbar"><label className="search-field" htmlFor="quotes-search"><Search size={16} /><input id="quotes-search" value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Buscar número, cliente ou serviço" /></label><label className="quotes-status-filter" htmlFor="quotes-status"><span>Status</span><select id="quotes-status" value={status} onChange={(event) => setStatus(event.target.value)}><option value="">Todos os status</option>{statuses.map((item) => <option key={item}>{item}</option>)}</select></label></div>{filteredQuotes.length ? <div className="quotes-table" role="table" aria-label="Cotações"><div className="quotes-table-header" role="row">{QUOTE_SORT_COLUMNS.map(([key, label]) => <div key={key} role="columnheader"><button className={sort.key === key ? "table-sort-button active" : "table-sort-button"} type="button" onClick={() => setSort((current) => ({ key, direction: current.key === key && current.direction === "asc" ? "desc" : "asc" }))}><span>{label}</span>{sort.key === key && <ChevronDown className={sort.direction === "asc" ? "sort-icon ascending" : "sort-icon"} size={14} />}</button></div>)}<span>Ação</span></div>{filteredQuotes.map((quote) => { const task = tasksByQuote.get(quote.id); return <div className="quotes-table-row" role="button" tabIndex={0} key={quote.id} onClick={() => setSelectedQuote(quote)} onKeyDown={(event) => { if (event.key === "Enter" || event.key === " ") setSelectedQuote(quote); }}><div className="quote-main"><span className="quote-code">{quote.code || "Sem número"}</span><strong>{quote.title || "Sem título"}</strong></div><span className="quote-client">{quote.client || "Cliente não informado"}</span><QuoteStatus status={quote.status} /><span className={`quote-deadline ${isOverdueQuote(quote) ? "is-overdue" : ""}`}><CalendarDays size={13} />{formatDate(quote.deadline)}</span><strong className="quote-value">{quote.value || "—"}</strong>{task ? <button className="quote-task-link" type="button" onClick={(event) => { event.stopPropagation(); onOpenTask?.(task.id); }}><Link2 size={14} />Ver tarefa</button> : <span className="quote-no-task">Sem tarefa</span>}</div>; })}</div> : <div className="quotes-empty" role="status"><FileText size={28} /><strong>Nenhuma cotação encontrada</strong><span>Ajuste a busca ou o filtro de status.</span></div>}</section>
    {workspaceEnabled && editingQuote && <div className="quote-workspace-layer" onMouseDown={(event) => { if (event.target === event.currentTarget) setEditingQuote(null); }}><QuoteWorkspace quote={editingQuote.id ? quotes.find((item) => item.id === editingQuote.id) || editingQuote : editingQuote} employees={state.employees || []} saving={savingQuote} onBack={() => setEditingQuote(null)} onSave={(draft) => { setSavingQuote(true); const operation = draft.id ? onUpdateQuote?.(draft.id, draft) : onCreateQuote?.(draft); Promise.resolve(operation).finally(() => setSavingQuote(false)).then((success) => { if (success !== false) setEditingQuote(null); }); }} onMarkSent={onMarkQuoteSent} onOutcome={onSetQuoteOutcome} /></div>}
    {selectedQuote && <div className="drawer-layer" onMouseDown={(event) => { if (event.target === event.currentTarget) setSelectedQuote(null); }}><aside className="task-drawer quote-detail-drawer" aria-label={`Detalhes da cotação ${selectedQuote.code || ""}`}><header className="drawer-header"><div><span className="eyebrow">CONSULTA DE COTAÇÃO</span><span className="drawer-code">{selectedQuote.code || "SEM NÚMERO"}</span></div><button className="icon-button" type="button" onClick={() => setSelectedQuote(null)} aria-label="Fechar"><X size={19} /></button></header><div className="drawer-body"><div className="quote-detail-title"><span className="quote-code">{selectedQuote.code || "Sem número"}</span><h2>{selectedQuote.title || "Sem título"}</h2></div><div className="quote-detail-grid"><div><span>Cliente</span><strong>{selectedQuote.client || "Cliente não informado"}</strong></div><div><span>Status</span><QuoteStatus status={selectedQuote.status} /></div><div><span>Prazo de resposta</span><strong className={isOverdueQuote(selectedQuote) ? "danger-text" : ""}>{formatDate(selectedQuote.deadline)}</strong></div><div><span>Valor cotado</span><strong>{selectedQuote.value || "—"}</strong></div></div><div className="quote-detail-note"><FileText size={16} /><span>Equipe padrão: Financeiro. A tabela HTML é copiada para colar no Outlook e o envio é registrado separadamente.</span></div></div><footer className="drawer-footer">{workspaceEnabled && <button className="button button-primary" type="button" onClick={() => openEditor(selectedQuote)}><Save size={15} />Abrir cotação</button>}{selectedTask && <button className="button button-secondary" type="button" onClick={() => { setSelectedQuote(null); onOpenTask?.(selectedTask.id); }}><Link2 size={15} />Ver tarefa vinculada</button>}<button className="button button-quiet" type="button" onClick={() => setSelectedQuote(null)}>Fechar</button></footer></aside></div>}
  </div>;
}
