import {
  BadgeCheck,
  Banknote,
  BriefcaseBusiness,
  Building2,
  Calculator,
  CarFront,
  ChartNoAxesCombined,
  ClipboardList,
  ConciergeBell,
  Crown,
  Factory,
  FileText,
  Globe2,
  Handshake,
  Headphones,
  HeartHandshake,
  Landmark,
  LifeBuoy,
  Megaphone,
  Package,
  Plane,
  Radio,
  ReceiptText,
  Route,
  Settings2,
  ShieldCheck,
  ShoppingBag,
  Star,
  Truck,
  UserRoundCheck,
  Users,
  WalletCards,
  Wrench,
  Zap,
} from "lucide-react";

export const TEAM_ICON_OPTIONS = [
  { id: "users", label: "Pessoas", Icon: Users },
  { id: "briefcase", label: "Comercial", Icon: BriefcaseBusiness },
  { id: "car", label: "Operação", Icon: CarFront },
  { id: "shield", label: "Qualidade", Icon: ShieldCheck },
  { id: "headphones", label: "Atendimento", Icon: Headphones },
  { id: "building", label: "Empresa", Icon: Building2 },
  { id: "calculator", label: "Financeiro", Icon: Calculator },
  { id: "chart", label: "Indicadores", Icon: ChartNoAxesCombined },
  { id: "clipboard", label: "Processos", Icon: ClipboardList },
  { id: "concierge", label: "Concierge", Icon: ConciergeBell },
  { id: "crown", label: "Executivo", Icon: Crown },
  { id: "factory", label: "Produção", Icon: Factory },
  { id: "file", label: "Documentos", Icon: FileText },
  { id: "globe", label: "Internacional", Icon: Globe2 },
  { id: "handshake", label: "Parcerias", Icon: Handshake },
  { id: "heart", label: "Cuidado", Icon: HeartHandshake },
  { id: "landmark", label: "Institucional", Icon: Landmark },
  { id: "lifebuoy", label: "Suporte", Icon: LifeBuoy },
  { id: "megaphone", label: "Marketing", Icon: Megaphone },
  { id: "package", label: "Logística", Icon: Package },
  { id: "plane", label: "Aeroporto", Icon: Plane },
  { id: "radio", label: "Comunicação", Icon: Radio },
  { id: "receipt", label: "Cobrança", Icon: ReceiptText },
  { id: "route", label: "Rotas", Icon: Route },
  { id: "settings", label: "Configuração", Icon: Settings2 },
  { id: "shopping", label: "Compras", Icon: ShoppingBag },
  { id: "star", label: "Destaque", Icon: Star },
  { id: "truck", label: "Frota", Icon: Truck },
  { id: "verified-user", label: "Confiável", Icon: UserRoundCheck },
  { id: "wallet", label: "Pagamentos", Icon: WalletCards },
  { id: "wrench", label: "Manutenção", Icon: Wrench },
  { id: "badge", label: "Certificado", Icon: BadgeCheck },
  { id: "banknote", label: "Valores", Icon: Banknote },
  { id: "zap", label: "Prioridade", Icon: Zap },
];

export function TeamIcon({ name = "users", size = 14, ...props }) {
  const option = TEAM_ICON_OPTIONS.find((item) => item.id === name) || TEAM_ICON_OPTIONS[0];
  return <option.Icon size={size} aria-hidden="true" {...props} />;
}
